/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MikaButton {
        /**
          * if `true`, the button is disabled
          * @default false
         */
        "isDisabled"?: boolean;
        /**
          * button size
          * @default m
         */
        "size"?: "xs" | "s" | "m" | "l";
        /**
          * button variant
          * @default primary
         */
        "variant"?: "primary" | "secondary";
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLMikaButtonElement extends Components.MikaButton, HTMLStencilElement {
    }
    var HTMLMikaButtonElement: {
        prototype: HTMLMikaButtonElement;
        new (): HTMLMikaButtonElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "mika-button": HTMLMikaButtonElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface MikaButton {
        /**
          * if `true`, the button is disabled
          * @default false
         */
        "isDisabled"?: boolean;
        /**
          * button size
          * @default m
         */
        "size"?: "xs" | "s" | "m" | "l";
        /**
          * button variant
          * @default primary
         */
        "variant"?: "primary" | "secondary";
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "mika-button": MikaButton;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "mika-button": LocalJSX.MikaButton & JSXBase.HTMLAttributes<HTMLMikaButtonElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
